# Check server status

---
  - hosts: webservers:loadbalancers
    become: true
    tasks:
      - name: Check apache status
        command: service apache2 status
        args:
          warn: no # Ignore warning
        changed_when: false # Change the status from 'Changed' to 'OK'

      - name: Return the failed result as OK
        command: /bin/false # This command always return false/failed
        ignore_errors: yes # Ignore failed status. and return non-failed status
