# Install Services on Webserver and Loadbancer

---
- hosts: webservers
  become: true
  tasks: 
    - name: Installing multiple service
      apt:
        name:
          - apache2
          - php-{bcmath,bz2,intl,gd,mbstring,mcrypt,mysql,zip}
          - libapache2-mod-php
        state: present
    - name: Ensure apache starts
      service: name=apache2 state=started enabled=yes

- hosts: loadbalancers
  become: true
  tasks: 
    - name: Installing apache on loadbalancers
      apt: name=apache2 state=present 
    - name: Ensure apache starts
      service: name=apache2 state=started enabled=yes
