# Settings for app servers

---
  - hosts: webservers
    become: true

    vars:
      path_to_app: "/var/www/html"
      
    tasks:
      - name: Upload application file
        copy:
          src: ../index.php
          dest: "{{ path_to_app }}" #replacing the path with local variable /var/www/html
          mode: 0755

      - name: Create a page
        copy:
          dest: "{{ path_to_app }}/about.php" 
          content: "<h2> Webserver Host: {{ ansible_hostname }} </h2>"
      
      - name: Check directory content
        command: ls -al {{ path_to_app }}
        register: dir_contents # using registered variables

      - name: Debug directory content
        debug:
          msg: "{{ dir_contents }}"

    handlers:
      - name: Restart apache
        service: name=apache2 state=restarted         
