# Loadbalancer setting

---
  - hosts: loadbalancers
    become: true 
    tasks:
      - name: Creating template
        template:
          src: ../loadbalance-config.j2
          dest: /etc/apache2/sites-available/loadbalance.conf
          owner: bin
          group: wheel
          mode: 064
        notify: restart apache2

    handlers:
      - name: Restart apache
        service: name=apache2 state=restarted
